FROM clickhouse/clickhouse-server:latest

COPY clickhouse_config/zookeeper_config.xml /etc/clickhouse-server/config.d/zookeeper_config.xml
COPY clickhouse_config/cluster_definition.xml /etc/clickhouse-server/config.d/cluster_definition.xml
